### ISSUE TITLE
Create docker-compose.yaml

### ISSUE THREAD

**Issue by IgorKrupenja** [buerokratt/DMR#12]
**AS A** Developer
**I WANT** to have a docker-compose file
**SO THAT** that I have a way to run the project alongside other Burokratt modules

## Acceptance criteria

- [ ] Root of the project has a `docker-compose.yaml` with one DMR server, two agents and one RabbitMQ node.
- [ ] All the environment variables are provided.
- [ ] `bykstack` is used as a network name. It is configured this way:

```yaml
networks:
  bykstack:
    name: bykstack
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
```

- [ ] Exposed ports are in range 8070 to 8079.
