### ISSUE TITLE
DMR Agent Prometheus metrics

### ISSUE THREAD

**Issue by IgorKrupenja** [buerokratt/DMR#43]
**AS AN** Architect
**I WANT** to explore possible options for useful DMR Agent Prometheus metrics
**SO THAT** we can implement this to have better observability.

## ❗ Important

- Do not start with this before all other tasks for DMR Agent are implemented.

### Research

We want to have some [Prometheus](https://prometheus.io/) metrics for DMR Agent.

- [ ] Please research this and create a short summary in a comment for this task. The summary should answer these questions:
	- [ ] 1. What should be the list of metrics we track?
	- [ ] 2. Based on the suggested metrics from the previous point, please also suggest some useful [alerting rules](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/).

### Implementation

- [ ] Implement based on research.
- [ ] Add info on metrics and suggested alerts to the Readme.
- [ ] Add a couple simple tests to make sure that Prometheus metrics/endpoint works.

**Comment by aNazirov** [comment]
@IgorKrupenja  I think we can start by implementing the same metrics from [this issue](https://github.com/buerokratt/DMR/issues/42)

**Comment by aNazirov** [comment]
@IgorKrupenja  As you said, if we don’t want to implement the default socket metrics in the DMR Agent, I’ve prepared an alternative set of metrics.


Suggested metrics:

REST API (MessagesController)

- **`dmr_http_requests_total` | `counter` | `method, route, status` | Total HTTP requests handled
- **`dmr_http_request_duration_seconds` | `histogram` | `method, route, status` | HTTP request processing time
- **`dmr_http_errors_total` | `counter` | `method, route` | Count of error responses (4xx/5xx)

WebSocket Metrics:

- **`dmr_agent_socket_connection_status` | `gauge` | `namespace` | 1 if socket connected, 0 if not

Suggested alert rules:

```yaml
groups:
  - name: dmr-agent-alerts
    rules:
      - alert: MultipleSocketConnections
        expr: dmr_agent_socket_connection_status > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Multiple WebSocket connections detected"
          description: >
            DMR Agent is expected to maintain only 1 WebSocket connection. Found {{ $value }}.

      - alert: SocketDisconnected
        expr: dmr_agent_socket_connection_status == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "DMR Agent is disconnected from the DMR server"
          description: >
            No active WebSocket connection from DMR Agent for over 2 minutes.

      - alert: HighApiLatency
        expr: |
          histogram_quantile(0.95, rate(dmr_http_request_duration_seconds_bucket[5m]))
          > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP latency"
          description: >
            95th percentile latency of DMR Agent REST API is over 1s (current: {{ $value }}s)

      - alert: TooManyHttpErrors
        expr: |
          rate(dmr_http_errors_total[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High rate of HTTP errors"
          description: >
            More than 1 HTTP error/sec from DMR Agent (4xx or 5xx responses)

```
